### ISSUE TITLE
The TF-IDF vectorizer is not fitted error due to redundant instance creation

### ISSUE THREAD

**Issue by tomaquet18** [dragonked2/metax#4]
I encountered an issue where the program raises a the tf-idf vectorizer is not fitted error. This occurs because the TfidfVectorizer is being fitted, but a new instance is then created, leading to the error when the pipeline attempts to use the unfitted vectorizer.

**Steps to Reproduce:**
- Run the program with the current codebase.
- Observe the the tf-idf vectorizer is not fitted error.

**Proposed Solution:**
The issue can be resolved by reusing the same instance of TfidfVectorizer for fitting and saving the vectorizer, instead of creating a new instance after fitting the data.

**Expected Behavior:**
The program should run without errors related to the TF-IDF vectorizer fitting.

**Comment by dragonked2** [comment]
Fixed and Added Thank You
